import = [
	#"~/.config/alacritty/catppuccin-macchiato.toml"
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
term = "xterm-256color"

[window]
dynamic_padding = true
opacity = 0.85
dynamic_title = true

[font]
size = 16
normal = {family = "Hack Nerd Font Mono", style = "Regular"}
bold = {family = "Hack Nerd Font Mono", style = "Bold"}
italic = {family = "Hack Nerd Font Mono", style = "italic"}
bold_italic = {family = "Hack Nerd Font Mono", style = "Bold Italic"}
